# Gunakan base image Python
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Salin requirements.txt dan install dependensi
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file proyek
COPY loan_service.py .
COPY config.py .
COPY requirements.txt .

# Ekspos port untuk book_service
EXPOSE 5001

# Jalankan book_service
CMD ["python", "loan_service.py"]