# Gunakan base image Python
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Salin requirements.txt dan install dependensi
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file proyek
COPY user_service.py .
COPY config.py .
COPY requirements.txt .
COPY .env .

# Ekspos port untuk book_service
EXPOSE 5002

# Jalankan book_service
CMD ["python", "user_service.py"]